// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_QMZ_bcLsrrETna0Bu-zTHdPzjApJGAY',
    appId: '1:720212570476:web:763e947d2b58f9ce948349',
    messagingSenderId: '720212570476',
    projectId: 'fruits-cfdc1',
    authDomain: 'fruits-cfdc1.firebaseapp.com',
    storageBucket: 'fruits-cfdc1.appspot.com',
    measurementId: 'G-7QL0SJDKB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPBU9G_AzCnDO5_xaN6YnTNLD0MXnTKLs',
    appId: '1:720212570476:android:8a1dcd4ed9b74291948349',
    messagingSenderId: '720212570476',
    projectId: 'fruits-cfdc1',
    storageBucket: 'fruits-cfdc1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdgyy-LTVZmJPEWc_R6o5Mepgqj6qlvcc',
    appId: '1:720212570476:ios:7d251dfcd54b44a9948349',
    messagingSenderId: '720212570476',
    projectId: 'fruits-cfdc1',
    storageBucket: 'fruits-cfdc1.appspot.com',
    iosBundleId: 'h.magdy.fruits',
  );

}